root = "."
tmp_dir = "tmp"

[build]
cmd = "templ generate && go build -o ./tmp/main ."
bin = "tmp/main"
full_rebuild = true
include_ext = ["go", "templ", "tmpl", "html", "env"]
exclude_dir = ["assets", "tmp", "vendor"]
exclude_regex = [".*_templ.go"]
include_dir = []
exclude_file = []
delay = 1000 # ms
stop_on_error = true
send_interrupt = false
kill_delay = 500 # ms

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true